-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: db/uto_tasks.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/uto_tasks (
  uto_task_id BLOB NOT NULL,
  uto_page_namespace INTEGER UNSIGNED NOT NULL,
  uto_page_title VARCHAR(255) NOT NULL,
  uto_user_id INTEGER UNSIGNED NOT NULL,
  uto_type VARCHAR(64) NOT NULL,
  uto_since BLOB NOT NULL,
  uto_wiki_id VARCHAR(255) NOT NULL,
  uto_data CLOB NOT NULL
);

CREATE UNIQUE INDEX uto_unique ON /*_*/uto_tasks (
  uto_task_id, uto_wiki_id, uto_user_id
);

CREATE INDEX uto_user_lookup ON /*_*/uto_tasks (uto_user_id);
