-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/UnifiedTaskOverview/db/uto_usertasks.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/uto_usertasks (
  uto_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  uto_page_id INTEGER UNSIGNED NOT NULL,
  uto_user_id INTEGER UNSIGNED NOT NULL,
  uto_type BLOB NOT NULL, uto_key BLOB NOT NULL,
  uto_wiki_id BLOB NOT NULL, uto_page_title BLOB NOT NULL
);

CREATE UNIQUE INDEX uto_unique ON /*_*/uto_usertasks (
  uto_user_id, uto_type, uto_key, uto_wiki_id
);

CREATE INDEX uto_user_lookup ON /*_*/uto_usertasks (uto_user_id);
