-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: db/uto_tasks.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/uto_tasks (
  uto_task_id VARBINARY(128) NOT NULL,
  uto_page_namespace INT UNSIGNED NOT NULL,
  uto_page_title VARCHAR(255) NOT NULL,
  uto_user_id INT UNSIGNED NOT NULL,
  uto_type VARCHAR(64) NOT NULL,
  uto_since BINARY(14) NOT NULL,
  uto_wiki_id VARCHAR(255) NOT NULL,
  uto_data LONGTEXT NOT NULL,
  UNIQUE INDEX uto_unique (
    uto_task_id, uto_wiki_id, uto_user_id
  ),
  INDEX uto_user_lookup (uto_user_id)
) /*$wgDBTableOptions*/;
