-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/UnifiedTaskOverview/db/uto_usertasks.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/uto_usertasks (
  uto_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  uto_page_id INT UNSIGNED NOT NULL,
  uto_user_id INT UNSIGNED NOT NULL,
  uto_type VARBINARY(64) NOT NULL,
  uto_key VARBINARY(128) NOT NULL,
  uto_wiki_id VARBINARY(64) NOT NULL,
  uto_page_title VARBINARY(255) NOT NULL,
  UNIQUE INDEX uto_unique (
    uto_user_id, uto_type, uto_key, uto_wiki_id
  ),
  INDEX uto_user_lookup (uto_user_id),
  PRIMARY KEY(uto_id)
) /*$wgDBTableOptions*/;
