-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/UnifiedTaskOverview/db/uto_usertasks.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE uto_usertasks (
  uto_id SERIAL NOT NULL,
  uto_page_id INT NOT NULL,
  uto_user_id INT NOT NULL,
  uto_type TEXT NOT NULL,
  uto_key TEXT NOT NULL,
  uto_wiki_id TEXT NOT NULL,
  uto_page_title TEXT NOT NULL,
  PRIMARY KEY(uto_id)
);

CREATE UNIQUE INDEX uto_unique ON uto_usertasks (
  uto_user_id, uto_type, uto_key, uto_wiki_id
);

CREATE INDEX uto_user_lookup ON uto_usertasks (uto_user_id);
